-- ===============================
-- DB LAB 4 : DATA RETRIEVAL
-- ===============================

-- -------- Part A --------

-- Q1
SELECT STUDENT_ID AS ROLL_NO, NAME AS STUDENT_NAME, DATE_OF_BIRTH AS DOB, GENDER, CONTACT_NUMBER AS MOBILE_NO, DEPARTMENT_ID AS DEPT_ID FROM Student;

-- Q2
SELECT STUDENT_ID AS ROLL_NO, NAME AS STUDENT_NAME, DEPARTMENT_ID AS DEPT_ID FROM Student;

-- Q3
SELECT FACULTY_ID AS FACULTY_NO, NAME AS FACULTY_NAME, DESIGNATION, EMAIL AS EMAIL_ADDRESS FROM Faculty;

-- Q4
SELECT COURSE_ID AS COURSE_NO, COURSE_NAME AS COURSE_TITLE, CREDITS, DEPARTMENT_ID AS DEPT_ID, FACULTY_ID AS FACULTY_NO FROM Course;

-- Q5
SELECT ENROLLMENT_ID AS ENROLL_NO, STUDENT_ID AS ROLL_NO, COURSE_ID AS COURSE_NO, SEMESTER AS SEM_NO, GRADE AS FINAL_GRADE FROM Enrollment;

-- -------- Part B --------

-- Q6
SELECT * FROM Student WHERE DEPARTMENT_ID = 101;

-- Q7
SELECT * FROM Student WHERE GENDER = 'Female';

-- Q8
SELECT * FROM Faculty WHERE DESIGNATION = 'Assistant Professor';

-- Q9
SELECT * FROM Faculty WHERE DEPARTMENT_ID = 102;

-- Q10
SELECT * FROM Course WHERE CREDITS >= 4;

-- Q11
SELECT * FROM Student WHERE DATE_OF_BIRTH > TO_DATE('2003-01-01','YYYY-MM-DD');

-- Q12
SELECT * FROM Enrollment WHERE SEMESTER = '4';

-- -------- Part C --------

-- Q13
SELECT * FROM Student ORDER BY NAME ASC;

-- Q14
SELECT * FROM Student ORDER BY DATE_OF_BIRTH DESC;

-- Q15
SELECT * FROM Faculty ORDER BY DESIGNATION ASC;

-- Q16
SELECT * FROM Course ORDER BY CREDITS DESC;

-- Q17
SELECT * FROM Student FETCH FIRST 3 ROWS ONLY;

-- Q18
SELECT * FROM Course FETCH FIRST 5 ROWS ONLY;

-- -------- Part D --------

-- Q19
SELECT NAME, TRUNC(MONTHS_BETWEEN(SYSDATE, DATE_OF_BIRTH)/12) AS AGE FROM Student;

-- Q20
SELECT COURSE_NAME, CREDITS + 1 AS UPDATED_CREDITS FROM Course;

-- Q21
SELECT ENROLLMENT_ID, STUDENT_ID, COURSE_ID, SEMESTER, GRADE AS FINAL_GRADE FROM Enrollment;

-- Q22
SELECT NAME, EXTRACT(YEAR FROM DATE_OF_BIRTH) AS YEAR_OF_BIRTH FROM Student;

-- Q23
SELECT NAME, SUBSTR(EMAIL, INSTR(EMAIL,'@')+1) AS EMAIL_DOMAIN FROM Faculty;

-- ===============================
-- END OF LAB 4
-- ===============================
